
CREATE TABLE `FACTURA` (
  `ID_FACTURA` INT(10) NOT NULL AUTO_INCREMENT,
  `ID_TIENDA` INT(10) NOT NULL,
  `ID_CLIENTE` INT(10) NOT NULL,
  `CANTIDAD_FACTURA` DECIMAL(10, 2) DEFAULT NULL,
  `FECHA_FACTURA` DATE NOT NULL,
  `DESCRIPCION_FACTURA` VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (`ID_FACTURA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `FACTURA` (`ID_FACTURA`, `ID_TIENDA`, `ID_CLIENTE`, `CANTIDAD_FACTURA`, `FECHA_FACTURA`, `DESCRIPCION_FACTURA`) VALUES
(1, 1, 101, 150.75, '2024-09-29', 'Compra de productos'),
(2, 2, 102, 200.00, '2024-09-30', 'Servicio prestado');



CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` INT(11) NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(100) DEFAULT NULL,
  `DESCRIPCION_PRODUCTO` VARCHAR(200) DEFAULT NULL,
  `PRECIO_PRODUCTO` DECIMAL(10, 2) DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUCTO`)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `PRODUCTO` (`ID_PRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCION_PRODUCTO`, `PRECIO_PRODUCTO`) VALUES
(1, 'ZAPATO', 'CUERO', 10.2),
(2, 'PANTALON', 'GALA', 10.2);


SELECT *FROM PRODUCTO



CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` INT(11) NOT NULL,
  `NOMBRE_CLIENTE` VARCHAR(100) DEFAULT NULL,
  `DIRECCION_CLIENTE` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `CLIENTE` (`ID_CLIENTE`, `NOMBRE_CLIENTE`, `DIRECCION_CLIENTE`) VALUES
(1, 'CARLOS', 'PAUCARPATA'),
(2, 'BRUNO', 'MIRAFLORES');

CREATE TABLE `TIENDA` (
  `ID_TIENDA` INT(11) NOT NULL,
  `NOMBRE` VARCHAR(100) DEFAULT NULL,
  `DIRECCION_TIENDA` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (`ID_TIENDA`)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `TIENDA` (`ID_TIENDA`, `NOMBRE`, `DIRECCION_TIENDA`) VALUES
(1, 'TIENDABOX', 'PAUCARPATA'),
(2, 'TIENDAFOX', 'MIRAFLORES');

CREATE TABLE `FACTURA_PRODUCTO` (
  `ID_PRODUCTO` INT(11) NOT NULL,
  `ID_FACTURA` INT(11) NOT NULL,
  `CANTIDAD_PRODUCTO` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUCTO`, `ID_FACTURA`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(`ID_PRODUCTO`) ON DELETE CASCADE,
  FOREIGN KEY (`ID_FACTURA`) REFERENCES `FACTURA`(`ID_FACTURA`) ON DELETE CASCADE
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `FACTURA_PRODUCTO` (`ID_PRODUCTO`, `ID_FACTURA`, `CANTIDAD_PRODUCTO`) VALUES
(1, 1, 2),  -- 2 ZAPATOS en la factura 1
(2, 1, 1),  -- 1 PANTALÓN en la factura 1
(1, 2, 1);  -- 1 ZAPATO en la factura 2



SELECT *FROM FACTURA_PRODUCTO


